// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VBL.Data;

namespace VBL.Data.Migrations
{
    [DbContext(typeof(VBLDbContext))]
    partial class VBLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("ProviderKey");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("ProviderKey", "LoginProvider");

                    b.HasAlternateKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasAlternateKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("VBL.Data.AgeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AgeTypes");
                });

            modelBuilder.Entity("VBL.Data.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VBL.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("Dob");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastLoginProvider");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("RegistrationProvider");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VBL.Data.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<byte>("Order");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("VBL.Data.Email", b =>
                {
                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsPublic");

                    b.Property<bool>("IsVerified");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("Address");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("VBL.Data.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("VBL.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserCreatedId");

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.Property<int?>("UserModifiedId");

                    b.HasKey("Id");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserModifiedId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VBL.Data.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApplicationUserId");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("VBL.Data.OrganizationLocation", b =>
                {
                    b.Property<int>("OrganizationId");

                    b.Property<int>("LocationId");

                    b.HasKey("OrganizationId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("OrganizationLocations");
                });

            modelBuilder.Entity("VBL.Data.OrganizationMember", b =>
                {
                    b.Property<int>("OrganizationId");

                    b.Property<int>("UserId");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsActive");

                    b.Property<int>("Role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("VBL.Data.Phone", b =>
                {
                    b.Property<string>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsPublic");

                    b.Property<bool>("IsSMS");

                    b.Property<bool>("IsVerified");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("Number");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("VBL.Data.UserEmail", b =>
                {
                    b.Property<string>("EmailId");

                    b.Property<int>("UserId");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsPublic");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("EmailId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("UserEmails");
                });

            modelBuilder.Entity("VBL.Data.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<string>("Message");

                    b.Property<string>("OnClick");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("Seen");

                    b.Property<int>("UserId");

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("VBL.Data.UserPhone", b =>
                {
                    b.Property<string>("PhoneId");

                    b.Property<int>("UserId");

                    b.Property<DateTime?>("DtCreated");

                    b.Property<DateTime?>("DtModified");

                    b.Property<bool>("IsPublic");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserIdCreated");

                    b.Property<int?>("UserIdModified");

                    b.HasKey("PhoneId", "UserId");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserIdCreated");

                    b.HasIndex("UserIdModified");

                    b.ToTable("UserPhones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("VBL.Data.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("VBL.Data.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VBL.Data.ApplicationUser", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.Email", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.Location", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserModifiedId");
                });

            modelBuilder.Entity("VBL.Data.Organization", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.OrganizationLocation", b =>
                {
                    b.HasOne("VBL.Data.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VBL.Data.OrganizationMember", b =>
                {
                    b.HasOne("VBL.Data.Organization", "Organization")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "User")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.Phone", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.UserEmail", b =>
                {
                    b.HasOne("VBL.Data.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "User")
                        .WithMany("UserEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.UserNotification", b =>
                {
                    b.HasOne("VBL.Data.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });

            modelBuilder.Entity("VBL.Data.UserPhone", b =>
                {
                    b.HasOne("VBL.Data.Phone", "Phone")
                        .WithOne("UserPhone")
                        .HasForeignKey("VBL.Data.UserPhone", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "User")
                        .WithMany("UserPhones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VBL.Data.ApplicationUser", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserIdCreated");

                    b.HasOne("VBL.Data.ApplicationUser", "UserModified")
                        .WithMany()
                        .HasForeignKey("UserIdModified");
                });
#pragma warning restore 612, 618
        }
    }
}
