//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInformation_Public_Web", Namespace="http://schemas.datacontract.org/2004/07/AAUWebServices.Membership")]
    public partial class MemberInformation_Public_Web : ServiceReference1.AddressDetails
    {
        
        private string AssociationCodeField;
        
        private string Authorized_FirstNameField;
        
        private string Authorized_LastNameField;
        
        private string Authorized_MiddleNameField;
        
        private string CategoryCodeField;
        
        private string ClubCodeField;
        
        private int CompetingAgeField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        private string EmailAddressField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private string GenderField;
        
        private string InsuranceTypeField;
        
        private string LastNameField;
        
        private string MembershipIDField;
        
        private string MembershipTermEndingYearField;
        
        private string MiddleNameField;
        
        private string PhoneField;
        
        private string PrimarySportCodeField;
        
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssociationCode
        {
            get
            {
                return this.AssociationCodeField;
            }
            set
            {
                this.AssociationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authorized_FirstName
        {
            get
            {
                return this.Authorized_FirstNameField;
            }
            set
            {
                this.Authorized_FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authorized_LastName
        {
            get
            {
                return this.Authorized_LastNameField;
            }
            set
            {
                this.Authorized_LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Authorized_MiddleName
        {
            get
            {
                return this.Authorized_MiddleNameField;
            }
            set
            {
                this.Authorized_MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode
        {
            get
            {
                return this.CategoryCodeField;
            }
            set
            {
                this.CategoryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubCode
        {
            get
            {
                return this.ClubCodeField;
            }
            set
            {
                this.ClubCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompetingAge
        {
            get
            {
                return this.CompetingAgeField;
            }
            set
            {
                this.CompetingAgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceType
        {
            get
            {
                return this.InsuranceTypeField;
            }
            set
            {
                this.InsuranceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipID
        {
            get
            {
                return this.MembershipIDField;
            }
            set
            {
                this.MembershipIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipTermEndingYear
        {
            get
            {
                return this.MembershipTermEndingYearField;
            }
            set
            {
                this.MembershipTermEndingYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimarySportCode
        {
            get
            {
                return this.PrimarySportCodeField;
            }
            set
            {
                this.PrimarySportCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode
        {
            get
            {
                return this.ProgramCodeField;
            }
            set
            {
                this.ProgramCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDetails", Namespace="http://schemas.datacontract.org/2004/07/AAUWebServices.Membership")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.MemberInformation_Public_Web))]
    public partial class AddressDetails : object
    {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string AddressLine3Field;
        
        private string CityField;
        
        private string CountryField;
        
        private string CountyField;
        
        private string FullAddressField;
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3
        {
            get
            {
                return this.AddressLine3Field;
            }
            set
            {
                this.AddressLine3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAddress
        {
            get
            {
                return this.FullAddressField;
            }
            set
            {
                this.FullAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMembershipLookupService")]
    public interface IMembershipLookupService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_Verify_SecuredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_SecuredExceptionFau" +
            "lt", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_Verify_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_VerifyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_VerifyExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_VerifyAsync(string MembershipID, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOB_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOB_SecuredResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOB_SecuredExceptio" +
            "nFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_Verify_DOB_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string DOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOB", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOBResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_DOBExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_Verify_DOBAsync(string MembershipID, string DOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastName_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastName_SecuredRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastName_SecuredExc" +
            "eptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_Verify_LastName_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastName", ReplyAction="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/Membership_Verify_LastNameExceptionFa" +
            "ult", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<bool> Membership_Verify_LastNameAsync(string MembershipID, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCode_Secu" +
            "red", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCode_Secu" +
            "redResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCode_Secu" +
            "redExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_ByClubCode_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ClubCode, string CategoryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCode", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCodeRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_ByClubCodeExcep" +
            "tionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_ByClubCodeAsync(string MembershipID, string ClubCode, string CategoryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_SecuredResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search_SecuredExceptio" +
            "nFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_SecuredAsync(string uUserID, string iRecordSource, string FirstName, string MiddleName, string LastName, System.Nullable<System.DateTime> DoB, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Search", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_SearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_SearchExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_SearchAsync(string FirstName, string MiddleName, string LastName, System.Nullable<System.DateTime> DoB, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_SecuredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_SecuredExceptionFa" +
            "ult", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_GetExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_GetAsync(string MembershipID, string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOB_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOB_SecuredRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOB_SecuredExcepti" +
            "onFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_DOB_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string DOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOB", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOBResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_DOBExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_DOBAsync(string MembershipID, string DOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastName_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastName_SecuredRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastName_SecuredEx" +
            "ceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_LastName_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastName", ReplyAction="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/MembershipInfo_Get_LastNameExceptionF" +
            "ault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_LastNameAsync(string MembershipID, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_Secured", ReplyAction="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_SecuredResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_SecuredExceptio" +
            "nFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_SecuredAsync(string uUserID, string iRecordSource, string ClubCode, string RepresentativeMembershipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get", ReplyAction="http://tempuri.org/IMembershipLookupService/ClubMemberListing_GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_GetExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_GetAsync(string ClubCode, string RepresentativeMembershipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZip_Secured" +
            "", ReplyAction="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZip_Secured" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZip_Secured" +
            "ExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_WithZip_SecuredAsync(string uUserID, string iRecordSource, string ClubCode, string PrimaryRep_MemberID, string PrimaryRep_ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZip", ReplyAction="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZipResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IMembershipLookupService/ClubMemberListing_Get_WithZipExceptio" +
            "nFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_WithZipAsync(string ClubCode, string PrimaryRep_MemberID, string PrimaryRep_ZipCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IMembershipLookupServiceChannel : ServiceReference1.IMembershipLookupService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class MembershipLookupServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IMembershipLookupService>, ServiceReference1.IMembershipLookupService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MembershipLookupServiceClient() : 
                base(MembershipLookupServiceClient.GetDefaultBinding(), MembershipLookupServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AAUWebServicesBindingSecure.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MembershipLookupServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MembershipLookupServiceClient.GetBindingForEndpoint(endpointConfiguration), MembershipLookupServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MembershipLookupServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MembershipLookupServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MembershipLookupServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MembershipLookupServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MembershipLookupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> Membership_Verify_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ZipCode)
        {
            return base.Channel.Membership_Verify_SecuredAsync(uUserID, iRecordSource, MembershipID, ZipCode);
        }
        
        public System.Threading.Tasks.Task<bool> Membership_VerifyAsync(string MembershipID, string ZipCode)
        {
            return base.Channel.Membership_VerifyAsync(MembershipID, ZipCode);
        }
        
        public System.Threading.Tasks.Task<bool> Membership_Verify_DOB_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string DOB)
        {
            return base.Channel.Membership_Verify_DOB_SecuredAsync(uUserID, iRecordSource, MembershipID, DOB);
        }
        
        public System.Threading.Tasks.Task<bool> Membership_Verify_DOBAsync(string MembershipID, string DOB)
        {
            return base.Channel.Membership_Verify_DOBAsync(MembershipID, DOB);
        }
        
        public System.Threading.Tasks.Task<bool> Membership_Verify_LastName_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string LastName)
        {
            return base.Channel.Membership_Verify_LastName_SecuredAsync(uUserID, iRecordSource, MembershipID, LastName);
        }
        
        public System.Threading.Tasks.Task<bool> Membership_Verify_LastNameAsync(string MembershipID, string LastName)
        {
            return base.Channel.Membership_Verify_LastNameAsync(MembershipID, LastName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_ByClubCode_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ClubCode, string CategoryCode)
        {
            return base.Channel.MembershipInfo_Search_ByClubCode_SecuredAsync(uUserID, iRecordSource, MembershipID, ClubCode, CategoryCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_ByClubCodeAsync(string MembershipID, string ClubCode, string CategoryCode)
        {
            return base.Channel.MembershipInfo_Search_ByClubCodeAsync(MembershipID, ClubCode, CategoryCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_Search_SecuredAsync(string uUserID, string iRecordSource, string FirstName, string MiddleName, string LastName, System.Nullable<System.DateTime> DoB, string ZipCode)
        {
            return base.Channel.MembershipInfo_Search_SecuredAsync(uUserID, iRecordSource, FirstName, MiddleName, LastName, DoB, ZipCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> MembershipInfo_SearchAsync(string FirstName, string MiddleName, string LastName, System.Nullable<System.DateTime> DoB, string ZipCode)
        {
            return base.Channel.MembershipInfo_SearchAsync(FirstName, MiddleName, LastName, DoB, ZipCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string ZipCode)
        {
            return base.Channel.MembershipInfo_Get_SecuredAsync(uUserID, iRecordSource, MembershipID, ZipCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_GetAsync(string MembershipID, string ZipCode)
        {
            return base.Channel.MembershipInfo_GetAsync(MembershipID, ZipCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_DOB_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string DOB)
        {
            return base.Channel.MembershipInfo_Get_DOB_SecuredAsync(uUserID, iRecordSource, MembershipID, DOB);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_DOBAsync(string MembershipID, string DOB)
        {
            return base.Channel.MembershipInfo_Get_DOBAsync(MembershipID, DOB);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_LastName_SecuredAsync(string uUserID, string iRecordSource, string MembershipID, string LastName)
        {
            return base.Channel.MembershipInfo_Get_LastName_SecuredAsync(uUserID, iRecordSource, MembershipID, LastName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web> MembershipInfo_Get_LastNameAsync(string MembershipID, string LastName)
        {
            return base.Channel.MembershipInfo_Get_LastNameAsync(MembershipID, LastName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_SecuredAsync(string uUserID, string iRecordSource, string ClubCode, string RepresentativeMembershipID)
        {
            return base.Channel.ClubMemberListing_Get_SecuredAsync(uUserID, iRecordSource, ClubCode, RepresentativeMembershipID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_GetAsync(string ClubCode, string RepresentativeMembershipID)
        {
            return base.Channel.ClubMemberListing_GetAsync(ClubCode, RepresentativeMembershipID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_WithZip_SecuredAsync(string uUserID, string iRecordSource, string ClubCode, string PrimaryRep_MemberID, string PrimaryRep_ZipCode)
        {
            return base.Channel.ClubMemberListing_Get_WithZip_SecuredAsync(uUserID, iRecordSource, ClubCode, PrimaryRep_MemberID, PrimaryRep_ZipCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MemberInformation_Public_Web[]> ClubMemberListing_Get_WithZipAsync(string ClubCode, string PrimaryRep_MemberID, string PrimaryRep_ZipCode)
        {
            return base.Channel.ClubMemberListing_Get_WithZipAsync(ClubCode, PrimaryRep_MemberID, PrimaryRep_ZipCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AAUWebServicesBindingSecure))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AAUWebServicesBindingSecure))
            {
                return new System.ServiceModel.EndpointAddress("https://websrv1.aausports.org/Membership/svcMembershipLookup.svc/Membership/svcMe" +
                        "mbershipLookup.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MembershipLookupServiceClient.GetBindingForEndpoint(EndpointConfiguration.AAUWebServicesBindingSecure);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MembershipLookupServiceClient.GetEndpointAddress(EndpointConfiguration.AAUWebServicesBindingSecure);
        }
        
        public enum EndpointConfiguration
        {
            
            AAUWebServicesBindingSecure,
        }
    }
}
